<?php
/**
 * Created by PhpStorm.
 * User: 刘进义
 * Contact: ddf-128@163.com
 * Wechat:dd283681008
 * Date: 2018/9/18 19:35
 */


namespace app\common\controller;


use think\Controller;

class Common  extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        if (!defined('MODULE_NAME')){
            define('MODULE_NAME', $this->request->module());
        }
        if (!defined('CONTROLLER_NAME')){
            define('CONTROLLER_NAME', $this->request->controller());
        }
        if (!defined('ACTION_NAME')){
            define('ACTION_NAME', $this->request->action());
        }
    }


    //空操作
    public function _empty()
    {
        $this->error('operation not valid');
    }

    protected function check_admin_login(){
        $user = session('admin_auth_MM');
        //dump( $user );exit;
        return session('admin_auth_sign') == data_signature($user) ? $user['aid'] : 0;
    }


}