<?php
/**
 * Created by PhpStorm.
 * User: 刘进义
 * Contact: ddf-128@163.com
 * Wechat:dd283681008
 * Date: 2018/9/13 19:37
 */


namespace app\index\controller;


use app\index\Model\WarehouseModel;
use think\Controller;
use think\Db;
use think\Request;

class Store extends Home
{

    protected $store;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->store = new WarehouseModel();
    }

    /**库存管理页面
     * @return mixed
     */
    public function index()
    {
        $map['clinic_id'] = ['eq',1];
        $map['sp_state'] = ['eq',1];
        $map['clinic_id'] = ['eq',$this->zstUser['shop_id']];
        $spfl = Db::name('spfl')->where($map)->select();

        $this->assign('ypfl',$spfl);
        return $this->fetch();
    }

    /**库存管理数据
     * @return mixed
     */
    public function lists(Request $request)
    {
        $map = [];

        $keys = $request->param('keyword');
        if(!empty($keys)){
            $map['b.code|b.uname|b.name|b.manufacturer']=['like',$keys."%"];
        }
        //质量
        $ypzl = $request->param('ypzl','');
        if($ypzl != ''){
            $map['a.zl_status']= ['eq',$ypzl];
        }
        //药品分类
        $sp_type = $request->param('sp_type','');
        if($sp_type != ''){
            $map['b.classify_id']= ['eq',$sp_type];
        }
        //库存预警
        $kcyj = $request->param('kcyj','');
        $where = '';
        if($kcyj == 1){
            //$map['a.innumber']= ['gt',"`b`.`stock_max`"];
            $where = "a.innumber > b.stock_max";
        }elseif($kcyj == -1){
            $where = "a.innumber < b.stock_min";
            //$map['a.innumber']= ['lt',"`b`.`stock_min`"];
        }

        //近效期条件
        $jxq = $request->param('jxq','');
        if($jxq == '-1'){
            $where = "unix_timestamp(now()) > a.yxqz";
        }elseif ($jxq >0){
            $where = "timestampdiff(day,CURDATE(),FROM_UNIXTIME(a.yxqz, '%Y-%m-%d')) <= " . $jxq;
        }


        $map['a.clinic_id'] = ['eq',$this->zstUser['shop_id']];


        $page=$request->param('page/d','1');
        $limit=$request->param('rows/d','10');
        $page =$page-1;
        if($page>0){
            $page=$page*$limit;
        }
        $field = "a.code,c.sp_name as classify_id,b.uname,b.name,b.specification,e.jxgl_name as jxgl_name,d.dwgl_name as dwgl_name,b.manufacturer,b.produce_place,b.box_number,a.Piece,a.innumber,a.price as store_price,a.MoneyAccount,f.yxq_month as yxq_month,b.prescription,b.special,b.approval_number,b.approval_number_effect,b.scope,b.stock_max,b.stock_min,b.price,b.price_min,b.price_max,b.storage_method,b.maintenance_method,b.archival_information,b.remarks,if(b.sales_type=0,'正常销售','暂停销售') as sales_type,if(b.check_type=1,'已审核','未审核') as check_type,a.purnumbers,CASE a.zl_status WHEN 1 THEN '合格' WHEN 2 THEN '可疑' ELSE '不合格' END as zl_status,a.pihao,FROM_UNIXTIME(a.yxqz, '%Y-%m-%d') as yxqz";
        $count = $this->store->alias('a')->field($field)
                             ->join('zst_medicine b','a.medid = b.id','LEFT')
                             ->join('zst_yxq f','b.effect_id=f.yxq_id','LEFT')
                             ->join('zst_spfl c','b.classify_id = c.sp_id','LEFT')
                             ->join('zst_dwgl d','b.unit_id=d.id','LEFT')
                             ->join('zst_jxgl e','b.dosage_id=e.jxgl_id','LEFT')
                             ->where($map)
                             ->where($where)
                             ->count('ware_id');



        $list = $this->store->alias('a')->field($field)
                            ->join('zst_medicine b','a.medid = b.id','LEFT')
                            ->join('zst_yxq f','b.effect_id=f.yxq_id','LEFT')
                            ->join('zst_spfl c','b.classify_id = c.sp_id','LEFT')
                            ->join('zst_dwgl d','b.unit_id=d.id','LEFT')
                            ->join('zst_jxgl e','b.dosage_id=e.jxgl_id','LEFT')
                            ->where($map)
                            ->where($where)
                            ->order('a.ware_id desc')
                            ->limit($page,$limit)->select();

        $result= [
            'rows'=>$list,
            'total'=>$count
        ];
        return $result;


    }

    /**
     * 获取筛选date
     */
    public function getIniDate()
    {
        $shop_id = $this->zstUser['shop_id'];
        //echo $shop_id;
        $info = Db::name('dic_cshsz')->field('cshsz_jxqts')->where('clinic_id',$shop_id)->find();
        return $info;
    }

    /**导出库存数据
     * @param Request $request
     * @throws \PHPExcel_Exception
     * @throws \PHPExcel_Reader_Exception
     * @throws \think\Exception
     * @throws \think\exception\DbException
     */
    public function dataToExcel(Request $request)
    {
        $excel = new Api();
        $map = [];

        $keys = $request->param('keyword');
        if(!empty($keys)){
            $map['b.code|b.uname|b.name|b.manufacturer']=['like',$keys."%"];
        }

        $ypzl = $request->param('ypzl','');
        if($ypzl != ''){
            $map['a.zl_status']= ['eq',$ypzl];
        }

        $sp_type = $request->param('sp_type','');
        if($sp_type != ''){
            $map['b.classify_id']= ['eq',$sp_type];
        }

        $map['a.clinic_id'] = ['eq',$this->zstUser['shop_id']];
        $field = "a.code,c.sp_name as classify_id,b.uname,b.name,b.specification,e.jxgl_name as dosage_id,d.dwgl_name as unit_id,b.manufacturer,g.supplier_name as SupplyID,b.produce_place,b.box_number,a.Piece,a.innumber,a.price as store_price,a.MoneyAccount,f.yxq_month as effect_id,b.prescription,b.special,b.approval_number,b.approval_number_effect,b.scope,b.stock_max,b.stock_min,b.price,b.price_min,b.price_max,b.storage_method,b.maintenance_method,b.archival_information,b.remarks,if(b.sales_type=0,'正常销售','暂停销售') as sales_type,if(b.check_type=1,'已审核','未审核') as check_type,a.purnumbers,CASE a.zl_status WHEN 1 THEN '合格' WHEN 2 THEN '可疑' ELSE '不合格' END as zl_status";
        $excel_table = Db::name('warehouse')->alias('a')->field($field)
            ->join('zst_medicine b','a.medid = b.id','LEFT')
            ->join('zst_yxq f','b.effect_id=f.yxq_id','LEFT')
            ->join('zst_spfl c','b.classify_id = c.sp_id','LEFT')
            ->join('zst_dwgl d','b.unit_id=d.id','LEFT')
            ->join('zst_jxgl e','b.dosage_id=e.jxgl_id','LEFT')
            ->join('zst_supplier g','a.SupplyID=g.id','LEFT')
            ->where($map)
            ->order('a.ware_id desc')
            ->buildSql();

        //echo $excel_table;exit;

        $excel_field = [
            'code'=>'药品编码',
            'classify_id'=>'药品分类',
            'uname'=>'通用名称',
            'name'=>'商品名',
            'specification'=>'规格',
            'dosage_id'=>'剂型',
            'unit_id'=>'单位',
            'manufacturer'=>'生产厂商',
            'box_number'=>'整箱数量',
            'Piece'=>'总件数',
            'innumber'=>'库存数量',
            'produce_place'=>'产地',
            'store_price'=>'库存单价',
            'MoneyAccount'=>'库存金额',
            'effect_id'=>'商品效期',
            'approval_number'=>'批准文号',
            'stock_max'=>'库存上限',
            'stock_min'=>'库存下限',
            'SupplyID'=>'供应商',
            'zl_status'=>'质量情况',
            'sales_type'=>'销售状态',
            'check_type'=>'审核状态',

        ];

        $fileName = '诊所库存表_' . time();
        $sheetNmae = '库存表';
        $excel->excelDown($excel_table,$excel_field,$map=[],$fileName,$sheetNmae,2);


    }












}